name: Upload GeoPackages

# This GitHub Actions workflow checkouts (with Git LFS)
# the GeoPackage files, and upload them as release assets on GitHub
# for a tagged release.

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: true
          # github.event.inputs.tag

jobs:
  upload-geopackages:
    concurrency: prevent-race-condition
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if we are on the correct branch
        run: |
          set -x
          echo "BRANCH_NAME=$BRANCH_NAME"
          git branch
          ls -l
          du -csh .git/lfs

      # See https://github.com/actions/checkout/issues/165
      - name: Cache Git LFS for GeoPackages
        uses: actions/cache@v2
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('**/*.gpkg') }}
          restore-keys: |
            ${{ runner.os }}-lfs-gpkg-${{ hashFiles('**/*.gpkg') }}
            ${{ runner.os }}-lfs-gpkg

      - name: Git LFS pull
        run: |
          set -x
          GIT_TRACE=1 git lfs pull -I "**/*.gpkg"

      - name: Show directory after Git LFS pull
        run: |
          set -x
          ls -l
          du -csh .git/lfs

      - name: Calculate checksum of GeoPackages
        run: |
          set -x
          sha256sum -b */*.gpkg *.gpkg > opendrr-boundaries-gpkg.sha256sum

      - name: "Upload GeoPackages as GitHub release assets (for tagged release)"
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            **/*.gpkg
            opendrr-boundaries-gpkg.sha256sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
